### ISSUE TITLE
[BUG] mydumper hangs with bunch of "Lost connection to MySQL server during query" in the log

### ISSUE THREAD

**Issue by gdubicki** [mydumper/mydumper#1473]
**Describe the bug**

mydumper hangs with some strange (to me) errors printed out (see "Log" section below).

At the same time in my `mysql.err` log file I found these entries:
```
2024-04-15T10:34:46.085051Z 31419 [Note] Error reading relay log event for channel '': slave SQL thread was killed
2024-04-15T10:34:46.085072Z 31419 [Note] Slave SQL thread for channel '' exiting, replication stopped in log 'master-bin.064578' at position 41134500
2024-04-15T10:44:26.124578Z 47103 [Note] Access denied for user 'root'@'localhost' (using password: NO)
2024-04-15T11:08:06.866528Z 48204 [Note] Slave SQL thread for channel '' initialized, starting replication in log 'master-bin.064578' at position 41134500, relay log './slave-relay-bin.194041' position: 41134715
```

I am running mydumper on the same node as my MySQL slave and it's connecting to it via UNIX socket and the root user. Contents of `/root/.my.cnf`:
```
[client]
user=root
password='<redacted>'

[mysql]
user=root
password='<redacted>'

prompt="xxx-yyy mysql> "

[mysqladmin]
user=root
password='<redacted>'

[mysqldump]
user=root
password='<redacted>'
```

The strace doesn't tell me much:
```
root@xxx-yyy:~# strace -p 1828964
strace: Process 1828964 attached
futex(0x55cf795fd6e0, FUTEX_WAIT_PRIVATE, 0, NULL
```

Is the slave is starting again because mydumper is reenabling it or is it starting again the cause of the problem?

**To Reproduce**

Command executed:
* mydumper with all the parameters
```
mydumper \
  --defaults-extra-file=/root/.my.cnf \
  --outputdir=${DB_DUMP} \
  --rows=22500000 \
  --compress \
  --build-empty-files \
  --regex '^(?!(data_analysis\.))' \
  --threads=4 \
  --long-query-retry-interval 300 \
  --long-query-retries 5 \
  --verbose 3
```
* myloader with all the parameters

What mydumper and myloader version has been used?
`mydumper v0.16.1-3, built against MySQL 8.0.36-28 with SSL support`

**Expected behavior**

The backup should succeed or at least if it failed, the mydumper process should end.

**Log**

```
[Mon 15 Apr 2024 10:34:46 AM UTC] Starting mydumper, /backups/main_backups/mydumper/20240415_103446
** Message: 10:34:46.082: MyDumper backup version: 0.16.1-3
** Message: 10:34:46.082: Merging config files user:
** Message: 10:34:46.082: Using 4 dumper threads
** Message: 10:34:46.084: Connection via default library settings
** Message: 10:34:46.084: Connected to Percona 5.7.43
** Message: 10:34:46.084: Started dump at: 2024-04-15 10:34:46
** Message: 10:34:46.084: Stopping replica
** Message: 10:34:46.085: Written slave status
** Message: 10:34:46.085: Acquiring DDL lock
** Message: 10:34:46.088: LOCK TABLES FOR BACKUP: OK
** Message: 10:34:46.088: LOCK BINLOG FOR BACKUP: OK
** Message: 10:34:46.088: Acquiring Global lock
** Message: 10:34:46.114: FLUSH NO_WRITE_TO_BINLOG TABLES: OK
** Message: 10:34:46.115: FLUSH TABLES WITH READ LOCK: OK
** Message: 10:34:46.115: conf created
** Message: 10:34:46.115: End job creation
** Message: 10:34:46.115: Creating workers
** Message: 10:34:46.115: Starting Non-InnoDB tables
** Message: 10:34:46.115: Thread 1: connected using MySQL connection ID 46664
** Message: 10:34:46.115: Thread 3: connected using MySQL connection ID 46665
** Message: 10:34:46.115: Thread 4: connected using MySQL connection ID 46663
** Message: 10:34:46.115: Thread 2: connected using MySQL connection ID 46666
** Message: 10:34:46.119: Thread 3: Creating Jobs
** Message: 10:34:46.119: Thread 1: Creating Jobs
** Message: 10:34:46.119: Thread 2: Creating Jobs
** Message: 10:34:46.119: Thread 4: Creating Jobs
** Message: 10:34:46.119: Starting replica
** Message: 10:34:46.119: Written master status
** Message: 10:34:46.119: Thread 2: dumping db information for `data_analysis`
** Message: 10:34:46.119: Thread 4: dumping db information for `yyy_service_production`
** Message: 10:34:46.119: Thread 1: dumping db information for `xxx_production`
** Message: 10:34:46.119: Thread 3: dumping db information for `zzz_service_production`
** Message: 10:34:46.122: Thread 3: dumping db information for `mysql`
** Message: 10:34:46.124: Thread 4: dumping db information for `percona`
** Message: 10:34:46.124: Thread 2: dumping db information for `ramdisk`
** Message: 10:34:46.125: Thread 2: dumping db information for `sys`
** Message: 11:08:06.866: Waiting database finish
** Message: 11:08:06.866: Thread 4: Schema queue
** Message: 11:08:06.866: Thread 1: Schema queue
** Message: 11:08:06.866: Thread 4: dumping schema create for `yyy_service_production`
** Message: 11:08:06.866: Thread 3: Schema queue
** Message: 11:08:06.866: Thread 1: dumping schema create for `xxx_production`
** Message: 11:08:06.866: Thread 3: dumping schema create for `zzz_service_production`
** Message: 11:08:06.867: Shutdown jobs for less locking enqueued

** (mydumper:1828964): CRITICAL **: 11:08:06.867: Error dumping create database (yyy_service_production): Lost connection to MySQL server during query

** (mydumper:1828964): CRITICAL **: 11:08:06.867: Error dumping create database (xxx_production): Lost connection to MySQL server during query
** Message: 11:08:06.867: Thread 4: dumping schema create for `mysql`
** Message: 11:08:06.867: Thread 1: dumping schema create for `percona`
** Message: 11:08:06.867: Thread 2: Schema queue

** (mydumper:1828964): CRITICAL **: 11:08:06.869: Error dumping create database (zzz_service_production): Lost connection to MySQL server during query

** (mydumper:1828964): CRITICAL **: 11:08:06.869: Error dumping create database (mysql): Lost connection to MySQL server during query
** Message: 11:08:06.869: Thread 2: dumping schema create for `ramdisk`
** Message: 11:08:06.869: Thread 3: dumping schema create for `sys`
** Message: 11:08:06.869: Thread 4: dumping schema for `zzz_service_production`.`ar_internal_metadata`

** (mydumper:1828964): CRITICAL **: 11:08:06.869: Error dumping create database (percona): Lost connection to MySQL server during query
** Message: 11:08:06.869: Thread 1: dumping schema for `zzz_service_production`.`www2`

** (mydumper:1828964): CRITICAL **: 11:08:06.870: Error dumping create database (ramdisk): Lost connection to MySQL server during query

** (mydumper:1828964): CRITICAL **: 11:08:06.870: Error dumping create database (sys): Lost connection to MySQL server during query
** Message: 11:08:06.870: Thread 3: dumping schema for `yyy_service_production`.`ar_internal_metadata`
** Message: 11:08:06.870: Thread 2: dumping schema for `zzz_service_production`.`schema_migrations`

** (mydumper:1828964): CRITICAL **: 11:08:06.870: Error dumping schemas (zzz_service_production.ar_internal_metadata): Lost connection to MySQL server during query
** Message: 11:08:06.870: Thread 4: dumping schema for `yyy_service_production`.`schema_migrations`
```

**Backup**

```
root@xxx-yyy:~# ls -la /backups/main_backups/mydumper/20240415_103446
total 12
drwxr-xr-x  2 root  root  4096 Apr 15 11:08 .
drwxrwx--- 18 mysql mysql 4096 Apr 15 10:34 ..
-rw-r-----  1 root  root     0 Apr 15 11:08 yyy_service_production.ar_internal_metadata-schema.sql.gz
-rw-r-----  1 root  root     0 Apr 15 11:08 yyy_service_production-schema-create.sql.gz
-rw-r-----  1 root  root     0 Apr 15 11:08 yyy_service_production.schema_migrations-schema.sql.gz
-rw-r-----  1 root  root     0 Apr 15 11:08 xxx_production-schema-create.sql.gz
-rw-r-----  1 root  root     0 Apr 15 11:08 zzz_service_production.ar_internal_metadata-schema.sql.gz
-rw-r-----  1 root  root     0 Apr 15 11:08 zzz_service_production.www2-schema.sql.gz
-rw-r-----  1 root  root     0 Apr 15 11:08 zzz_service_production-schema-create.sql.gz
-rw-r-----  1 root  root     0 Apr 15 11:08 zzz_service_production.schema_migrations-schema.sql.gz
-rw-r--r--  1 root  root  2326 Apr 15 10:34 metadata.partial
-rw-r-----  1 root  root     0 Apr 15 11:08 mysql-schema-create.sql.gz
-rw-r-----  1 root  root     0 Apr 15 11:08 percona-schema-create.sql.gz
-rw-r-----  1 root  root     0 Apr 15 11:08 ramdisk-schema-create.sql.gz
-rw-r-----  1 root  root     0 Apr 15 11:08 sys-schema-create.sql.gz
```

**How to repeat**

The database is big and complicated and I would need to put a lot of effort in providing the structure while making it anonymized, so unless this is needed, I would prefer to not do this. I am hoping that you'll might know what's going on without it.

**Environment (please complete the following information):**

 - OS version: Ubuntu 20.04
 - MyDumper version: mydumper v0.16.1-3, built against MySQL 8.0.36-28 with SSL support

**Additional context**

We have used mydumper v0.9.5 for a very long time successfully before with a command like:

```
mydumper \
  --outputdir=${DB_DUMP} \
  --rows=22500000 \
  --compress \
  --build-empty-files \
  --threads=1 \
  --compress-protocol > $MYDUMPER_LOG_FILE 2>&1
```
(Sadly I don't know why 22.5M rows and why just 1 thread - my predecessor didn't leave any meaningful comment or a commit message about these values. 😞)

These backups were taking ~19 hours recently, but this was not a problem until we started to run some long-running data analysis queries on the slave we were using for the backups.

We wanted to speed up the backups and that was the main reason of upgrading mydumper.

The main DB, `xxx_production` size is 1.4TB on the disk:
```
root@xxx-yyy:~# ls -lah /disk1/mysql/xxx_production
total 1.4T
(...)
```

**Comment by gdubicki** [comment]
A rollback to mydumper 0.9.5 has fixed my issue. The beginning of its run log is like this:

```
** Message: 22:00:01.970: Connected to a MySQL server
** Message: 22:00:01.970: Using Percona Backup Locks
** Message: 22:00:01.973: Started dump at: 2024-04-19 22:00:01

** Message: 22:00:01.974: Written master status
** Message: 22:00:01.974: Written slave status
** Message: 22:00:01.975: Thread 1 connected using MySQL connection ID 185236
** Message: 22:00:01.998: Thread 1 dumping data for `mysql`.`columns_priv`
** Message: 22:00:01.998: Empty table mysql.columns_priv
** Message: 22:00:02.001: Thread 1 dumping data for `mysql`.`db`
** Message: 22:00:02.003: Thread 1 dumping data for `mysql`.`event`
** Message: 22:00:02.003: Empty table mysql.event
** Message: 22:00:02.003: Thread 1 dumping data for `mysql`.`func`
** Message: 22:00:02.004: Empty table mysql.func
** Message: 22:00:02.004: Thread 1 dumping data for `mysql`.`ndb_binlog_index`
** Message: 22:00:02.004: Empty table mysql.ndb_binlog_index
** Message: 22:00:02.004: Thread 1 dumping data for `mysql`.`proc`
** Message: 22:00:02.013: Thread 1 dumping data for `mysql`.`procs_priv`
** Message: 22:00:02.013: Empty table mysql.procs_priv
** Message: 22:00:02.013: Thread 1 dumping data for `mysql`.`proxies_priv`
** Message: 22:00:02.014: Thread 1 dumping data for `mysql`.`tables_priv`
** Message: 22:00:02.015: Thread 1 dumping data for `mysql`.`user`
** Message: 22:00:02.017: Thread 1 dumping data for `yyy_service_production`.`ar_internal_metadata`
** Message: 22:00:02.017: Thread 1 dumping data for `yyy_service_production`.`schema_migrations`
** Message: 22:00:02.018: Thread 1 dumping data for `yyy_service_production`.`versions`
** Message: 22:00:02.018: Thread 1 dumping data for `xxx_production`.`abouts`
** Message: 22:00:02.406: Non-InnoDB dump complete, unlocking tables
(…)
```

**Comment by davidducos** [comment]
Hi @gdubicki,
Can you test with the latest prerelease?

**Comment by gdubicki** [comment]
Hey @davidducos, thanks for looking into this!

Sure, I will do that in a few days!

Do I need to run with any particular parameters?

If I want to share some logs or some other data with you privately, are there any ways for me to do that?

**Comment by davidducos** [comment]
Hi @gdubicki,
Can you test with the latest released version?

**Comment by dreamydb** [comment]
Hi @davidducos, we are running into this issue with mydumper versions `0.16.3-1` and the latest version `0.16.5-1` against Percona server 8.0.31 and 8.0.35.

**Command used**
```
mydumper --rows=5000000 --compress  --build-empty-files  --triggers --events --routines --trx-consistency-only --long-query-guard=1800 --verbose=3 --threads=16 --user=backup_user --password=<pass> --socket=/path/to/sock --outputdir=/path/to/nfs/mydumper-$now --logfile $logfile
```

**Mydumper log:** It connects, stops replica, starts replica, backups up some data, two thread gets "Lost connection" error while other threads still connected and backing up data.
```
2024-08-01 05:28:25 [INFO] - MyDumper backup version: 0.16.5-1
2024-08-01 05:28:25 [INFO] - Using 12 dumper threads
2024-08-01 05:28:25 [INFO] - Connection via default library settings using password:
        Socket: /path/to/sock
        User: backup_user
2024-08-01 05:28:25 [INFO] - Connected to Percona 8.0.31
2024-08-01 05:28:25 [INFO] - Started dump at: 2024-08-01 05:28:25
2024-08-01 05:28:25 [INFO] - Stopping replica
2024-08-01 05:28:25 [INFO] - Written slave status
2024-08-01 05:28:25 [INFO] - Acquiring DDL lock
2024-08-01 05:28:25 [INFO] - LOCK INSTANCE FOR BACKUP: OK
2024-08-01 05:28:25 [INFO] - Acquiring Global lock
2024-08-01 05:28:25 [INFO] - FLUSH NO_WRITE_TO_BINLOG TABLES: OK
2024-08-01 05:28:25 [INFO] - FLUSH TABLES WITH READ LOCK: OK
2024-08-01 05:28:25 [INFO] - conf created
2024-08-01 05:28:25 [INFO] - End job creation
2024-08-01 05:28:25 [INFO] - Creating workers
2024-08-01 05:28:25 [INFO] - Starting Non-InnoDB tables
2024-08-01 05:28:25 [INFO] - Thread 2: connected using MySQL connection ID 9712
2024-08-01 05:28:25 [INFO] - Thread 1: connected using MySQL connection ID 9711
2024-08-01 05:28:25 [INFO] - Thread 3: connected using MySQL connection ID 9713
2024-08-01 05:28:25 [INFO] - Thread 4: connected using MySQL connection ID 9714
2024-08-01 05:28:25 [INFO] - Thread 5: connected using MySQL connection ID 9715
2024-08-01 05:28:25 [INFO] - Thread 6: connected using MySQL connection ID 9716
2024-08-01 05:28:25 [INFO] - Thread 7: connected using MySQL connection ID 9717
2024-08-01 05:28:25 [INFO] - Thread 8: connected using MySQL connection ID 9718
2024-08-01 05:28:25 [INFO] - Thread 11: connected using MySQL connection ID 9721
2024-08-01 05:28:25 [INFO] - Thread 12: connected using MySQL connection ID 9722
2024-08-01 05:28:25 [INFO] - Thread 10: connected using MySQL connection ID 9720
2024-08-01 05:28:25 [INFO] - Thread 9: connected using MySQL connection ID 9719
2024-08-01 05:28:25 [INFO] - Thread 2: Creating Jobs
2024-08-01 05:28:25 [INFO] - Thread 12: Creating Jobs
2024-08-01 05:28:25 [INFO] - Thread 3: Creating Jobs
2024-08-01 05:28:25 [INFO] - Thread 4: Creating Jobs
2024-08-01 05:28:25 [INFO] - Thread 5: Creating Jobs
2024-08-01 05:28:25 [INFO] - Thread 7: Creating Jobs
2024-08-01 05:28:25 [INFO] - Thread 1: Creating Jobs
2024-08-01 05:28:25 [INFO] - Thread 10: Creating Jobs
2024-08-01 05:28:25 [INFO] - Thread 6: Creating Jobs
2024-08-01 05:28:25 [INFO] - Thread 9: Creating Jobs
2024-08-01 05:28:25 [INFO] - Thread 11: Creating Jobs
2024-08-01 05:28:25 [INFO] - Thread 8: Creating Jobs
2024-08-01 05:28:25 [INFO] - Waiting database finish
2024-08-01 05:28:25 [INFO] - Written master status
2024-08-01 05:28:25 [INFO] - Thread 3: dumping db information for `$db2`
2024-08-01 05:28:25 [INFO] - Thread 5: dumping db information for `$db1`
<SNIP>
2024-08-01 05:28:27 [INFO] - UNLOCK TABLES: OK
2024-08-01 05:28:27 [INFO] - Global locks released
2024-08-01 05:28:27 [INFO] - Starting replica
<SNIP>

2024-08-01 05:31:57 [INFO] - Thread 10: `$db`.`$table` [ 81% ] | Tables: 11/11
2024-08-01 05:31:57 [INFO] - Thread 6: `$db`.`$table` [ 81% ] | Tables: 11/11
2024-08-01 05:31:59 [INFO] - Thread 2: `$db`.`$table` [ 81% ] | Tables: 11/11
2024-08-01 05:32:00 [INFO] - Thread 10: `$db`.`$table` [ 81% ] | Tables: 11/11
2024-08-01 05:32:00 [INFO] - Thread 6: `$db`.`$table` [ 81% ] | Tables: 11/11
2024-08-01 05:32:01 [ERROR] - Thread 4: Could not read data from $db.$table to write on /path/to/nfs/mydumper/mydumper-080124_052825/$db.$table.00000.00473.sql at byte 1285772: Lost connection to MySQL server during query
2024-08-01 05:32:01 [ERROR] - Thread 4: Error dumping table ($db.$table) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db`.`$table`  WHERE (2365000000 <= `id` AND `id` <= 2369999999)
2024-08-01 05:32:01 [ERROR] - Thread 4: Error dumping table ($db.$table) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db`.`$table`  WHERE (2370000000 <= `id` AND `id` <= 2374999999)
2024-08-01 05:32:01 [ERROR] - Thread 7: Could not read data from $db.$table to write on /path/to/nfs/mydumper/mydumper-080124_052825/$db.$table.00000.00482.sql at byte 1284653: Lost connection to MySQL server during query
2024-08-01 05:32:01 [ERROR] - Thread 7: Error dumping table ($db.$table) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db`.`$table`  WHERE (2410000000 <= `id` AND `id` <= 2414999999)
2024-08-01 05:32:01 [INFO] - Thread 5: `$db`.`$table` [ 82% ] | Tables: 11/11
2024-08-01 05:32:01 [INFO] - Thread 9: `$db`.`$table` [ 82% ] | Tables: 11/11
<SNIP>
2024-08-01 05:32:01 [INFO] - Thread 5: `$db`.`$tb1` [ 82% ] | Tables: 11/11
2024-08-01 05:32:01 [INFO] - Thread 9: `$db`.`$tb1` [ 82% ] | Tables: 11/11
2024-08-01 05:32:01 [INFO] - $db2.$tb2 has ~8568 rows
2024-08-01 05:32:01 [INFO] - $db.tb3 has ~1 rows
2024-08-01 05:32:01 [INFO] - Thread 11: `$db`.`tb3` [ 0% ] | Tables: 8/11
2024-08-01 05:32:02 [INFO] - Thread 2: `$db`.`$tb1` [ 82% ] | Tables: 8/11
2024-08-01 05:32:03 [INFO] - Thread 10: `$db`.`$tb1` [ 82% ] | Tables: 8/11
2024-08-01 05:32:03 [INFO] - Thread 6: `$db`.`$tb1` [ 82% ] | Tables: 8/11
2024-08-01 05:32:04 [INFO] - Thread 9: `$db`.`$tb1` [ 82% ] | Tables: 8/11
2024-08-01 05:32:04 [INFO] - Thread 5: `$db`.`$tb1` [ 82% ] | Tables: 8/11
2024-08-01 05:32:04 [INFO] - $db.$tb4 has ~33 rows
2024-08-01 05:32:04 [INFO] - Thread 3: `$db`.`$tb4` [ 0% ] | Tables: 7/11
<SNIP>
2024-08-01 05:33:07 [INFO] - Releasing DDL lock
2024-08-01 05:33:07 [INFO] - UNLOCK INSTANCE: OK
2024-08-01 05:33:07 [INFO] - Queue count: 0 0 0 0 0
2024-08-01 05:33:07 [INFO] - Main connection closed
2024-08-01 05:33:08 [INFO] - Finished dump at: 2024-08-01 05:33:07
``` 

Replica is stopped and started by mydumper, then hits timeout writing shortly after. The timing of the error lines up with "Lost connection to MySQL server during query" in mydumper log.
```
2024-08-01T05:28:25.624975-07:00 14 [Note] [MY-010596] [Repl] Error reading relay log event for channel '': slave SQL thread was killed
2024-08-01T05:28:25.625002-07:00 14 [Note] [MY-010587] [Repl] Slave SQL thread for channel '' exiting, replication stopped in log 'binlog.001416' at position 383554131
2024-08-01T05:28:27.377436-07:00 9737 [Note] [MY-010581] [Repl] Slave SQL thread for channel '' initialized, starting replication in log 'binlog.001416' at position 3835
54131, relay log './mysql-relay-bin.000008' position: 383554341
2024-08-01T05:31:22.282737-07:00 9714 [Note] [MY-010914] [Server] Aborted connection 9714 to db: 'unconnected' user: 'backup_user' host: 'localhost' (Got timeout writing communication packets).
2024-08-01T05:31:59.100326-07:00 9717 [Note] [MY-010914] [Server] Aborted connection 9717 to db: 'sys' user: 'backup_user' host: 'localhost' (Got timeout writing communication packets).
```
No issue with version `0.9.5-1.1` or `0.14.5-2` or `0.16.1-3`. Let me know if I can provide any other details.

**Comment by davidducos** [comment]
Hi @dreamydb,
Thank you for sharing the logs. 
I reviewed the code for versions 0.16.1-3 which you said that there is no issue and I compared with 0.16.3.1-2 which is where it started to fail. There are not changes in the mydumper_write.c file which is where everything related to the read from the database and write into the disk occours.
I also checked if NET_WRITE_TIMEOUT and WAIT_TIMEOUT has anything to do with it, but we are setting that in side the code, and not in the config file.
I saw that the Thread 4 and 7 are failing after writing 1.2MB approximately.
In order to be able to analyze this, is it possible for you to share the table structure? I don't need the column name or table name, I only need to know the types and the order. On the other hand will be really useful to see what mydumper wrote in:
/path/to/nfs/mydumper/mydumper-080124_052825/$db.$table.00000.00473.sql
/path/to/nfs/mydumper/mydumper-080124_052825/$db.$table.00000.00482.sql
If you are able to see the content on that file, will be useful for me, if you can confirm that the data on the table is not corrupted, executing a select like this:
```
SELECT * from $db.$table where {primary key} >= {latest value that you found in the file} order by {primary key} limit 10
```
I think that for some types of columns and some data on those columns, mydumper no working properly and it is not showing the real error. This will allow me to make a reproducible test case.

**Comment by markrechler** [comment]
Hello, been running into similar issues across 0.16 versions dumping from MySQL 8. I've included a table in hopes of helping diagnose. Even `0.16.1-3` exhibits this behavior but manages to get part-way through the dump. In other versions (`0.16.3-5`) was seeing `2024-07-08 07:44:47 [INFO] - db.vdi has ~0 rows`. Let me know if any other info could be helpful. Thanks!
```
Table: vdi
Create Table: CREATE TABLE `vdi` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `fc` tinyint(1) NOT NULL DEFAULT '0',
  `vid` int NOT NULL,
  `dc` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
  `dt` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
  `tc` varchar(20) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `amount` int NOT NULL,
  `ta` int DEFAULT NULL,
  `sg` int DEFAULT NULL,
  `ag` int DEFAULT NULL,
  `asg` int DEFAULT NULL,
  `tr` int DEFAULT NULL,
  `rt` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '',
  `ri` bigint DEFAULT NULL,
  `ca` datetime NOT NULL,
  `ua` datetime NOT NULL,
  `rd` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_vdi_on_vid_and_tc` (`vid`,`tc`),
  KEY `index_vdi_on_vid` (`vid`),
  KEY `index_vdi_on_reference` (`ri`,`rt`),
  KEY `index_vdi_on_tc` (`tc`)
) ENGINE=InnoDB AUTO_INCREMENT=4393512892 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
```

**Comment by markrechler** [comment]
Some further updates, in my case there was never any locking, just the error messages and on `0.16.3-5` the lack of dumping correctly.

I did notice that the errors along the lines of:
```
2024-08-01 05:32:01 [ERROR] - Thread 4: Error dumping table ($db.$table) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db`.`$table`  WHERE (2370000000 <= `id` AND `id` <= 2374999999)
```
seem to appear due to using the rows option and having empty results. ie the table has empty id ranges scattered throughout so `WHERE (2370000000 <= `id` AND `id` <= 2374999999)` would be empty. The total data is dumped in `0.16.1-3` aside from the empty ID ranges. Dropping the rows option clears up the error.

**Comment by davidducos** [comment]
Hi @markrechler is it possible for you to test with the latest prerelease? I made a change a few days ago and it might be related to this. Please, let me know

**Comment by markrechler** [comment]
Hi @davidducos , I can confirm version `0.16.6-1` ran without errors. Thanks!

**Comment by davidducos** [comment]
Hi @markrechler, this fix might be related to https://github.com/mydumper/mydumper/pull/1581/commits/2b1ef3f7b04652f0e3836fb67d8653696411389d
The feature that we disabled was related to reduce the amount of selects setting the new local max/min. However, we stop doing it as not all the time was useful, on the other hand, the default setting for the chunking mechanism is better. Anyways, now that I know we might the issue, I will add a comment in the code, just in case that we decide to enable it or make it optional.

**Comment by dreamydb** [comment]
Hi @davidducos

"Lost connection to MySQL server during query" error continues to happen on backups with version `0.16.6-2`. It is a bit sporadic, doesn't happen every night. Yesterday's backup completed with no errors, but today's did. Fails most of the time though. 

Command used:
```
mydumper --rows=5000000 --compress  --build-empty-files  --triggers --events --routines --trx-consistency-only --long-query-guard=1800 --verbose=3 --threads=16 --user=backup_user --password=<pass> --socket=/path/to/sock --outputdir=/path/to/backup/$S1-mydumper/mydumper-$now --logfile $logfile
```

Log snippet:
```
2024-09-03 05:33:49 [INFO] - MyDumper backup version: 0.16.6-2
2024-09-03 05:33:50 [INFO] - Using 12 dumper threads
2024-09-03 05:33:50 [INFO] - Connection via default library settings using password:
        Socket: /path/to/socket
        User: root
2024-09-03 05:33:50 [INFO] - Connected to Percona 8.0.31
2024-09-03 05:33:50 [INFO] - Started dump at: 2024-09-03 05:33:50
2024-09-03 05:33:50 [INFO] - Stopping replica
2024-09-03 05:33:50 [INFO] - Written slave status
2024-09-03 05:33:50 [INFO] - Acquiring DDL lock
2024-09-03 05:33:50 [INFO] - LOCK INSTANCE FOR BACKUP: OK
2024-09-03 05:33:50 [INFO] - Acquiring Global lock
2024-09-03 05:33:50 [INFO] - FLUSH NO_WRITE_TO_BINLOG TABLES: OK
2024-09-03 05:33:50 [INFO] - FLUSH TABLES WITH READ LOCK: OK
2024-09-03 05:33:50 [INFO] - conf created
2024-09-03 05:33:50 [INFO] - End job creation
2024-09-03 05:33:50 [INFO] - Creating workers
2024-09-03 05:33:50 [INFO] - Starting Non-InnoDB tables
2024-09-03 05:33:50 [INFO] - Thread 1: connected using MySQL connection ID 385990
2024-09-03 05:33:50 [INFO] - Thread 2: connected using MySQL connection ID 385991
2024-09-03 05:33:50 [INFO] - Thread 3: connected using MySQL connection ID 385993
2024-09-03 05:33:50 [INFO] - Thread 5: connected using MySQL connection ID 385992
2024-09-03 05:33:50 [INFO] - Thread 8: connected using MySQL connection ID 385995
2024-09-03 05:33:50 [INFO] - Thread 4: connected using MySQL connection ID 385994
2024-09-03 05:33:50 [INFO] - Thread 7: connected using MySQL connection ID 385996
2024-09-03 05:33:50 [INFO] - Thread 6: connected using MySQL connection ID 385997
2024-09-03 05:33:50 [INFO] - Thread 9: connected using MySQL connection ID 385999
2024-09-03 05:33:50 [INFO] - Thread 10: connected using MySQL connection ID 385998
2024-09-03 05:33:50 [INFO] - Thread 11: connected using MySQL connection ID 386000
2024-09-03 05:33:50 [INFO] - Thread 12: connected using MySQL connection ID 386001
2024-09-03 05:33:50 [INFO] - Thread 11: Creating Jobs
2024-09-03 05:33:50 [INFO] - Thread 3: Creating Jobs
2024-09-03 05:33:50 [INFO] - Thread 2: Creating Jobs
2024-09-03 05:33:50 [INFO] - Thread 5: Creating Jobs
2024-09-03 05:33:50 [INFO] - Thread 6: Creating Jobs
2024-09-03 05:33:50 [INFO] - Thread 4: Creating Jobs
2024-09-03 05:33:50 [INFO] - Thread 1: Creating Jobs
2024-09-03 05:33:50 [INFO] - Thread 9: Creating Jobs
2024-09-03 05:33:50 [INFO] - Thread 12: Creating Jobs
2024-09-03 05:33:50 [INFO] - Thread 8: Creating Jobs
2024-09-03 05:33:50 [INFO] - Thread 10: Creating Jobs
2024-09-03 05:33:50 [INFO] - Thread 7: Creating Jobs
2024-09-03 05:33:50 [INFO] - Waiting database finish
2024-09-03 05:33:50 [INFO] - Written master status
<SNIP>
2024-09-03 05:37:23 [ERROR] - Thread 6: Could not read data from $db1.$table1 to write on /path/to/backup/$S1-mydumper/mydumper-090324_053349/$db1.$table1.00000.00025.sql at byte 1239182: Lost connection to MySQL server during query
<SNIP>
2024-09-03 05:38:08 [INFO] - $db1.$table2 has ~0 rows
2024-09-03 05:38:08 [ERROR] - Thread 6: Error dumping table ($db1.$table2) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db1`.`table2`           
<SNIP>
``` 
Table structure is 
```
| table1 | CREATE TABLE `table1` (
  `col1` bigint NOT NULL AUTO_INCREMENT,
  `col2` varchar(32) DEFAULT NULL,
  `col3` varchar(255) DEFAULT NULL,
  `col4` varchar(255) DEFAULT NULL,
  `col5` varchar(64) DEFAULT NULL,
  `col6` datetime DEFAULT '0000-00-00 00:00:00',
  `col7` datetime DEFAULT NULL,
  `col8` datetime DEFAULT NULL,
  `col9` datetime DEFAULT NULL,
  `col10` datetime DEFAULT NULL,
  `col11` datetime DEFAULT NULL,
  `col12` varchar(32) DEFAULT NULL,
  `col13` varchar(128) DEFAULT NULL,
  `col14` int DEFAULT NULL,
  `col15` varchar(32) DEFAULT NULL,
  `col16` int DEFAULT '0',
  `col17` int DEFAULT NULL,
  `col18` int DEFAULT NULL,
  `col19` bigint DEFAULT NULL,
  `col20` bigint DEFAULT NULL,
  `col21` int NOT NULL DEFAULT '0',
  `col22` bigint DEFAULT NULL,
  `col23` varchar(32) DEFAULT NULL,
  `col24` varchar(255) DEFAULT NULL,
  `col25` varchar(32) DEFAULT NULL,
  `col26` varchar(255) DEFAULT NULL,
  `col27` varchar(32) DEFAULT NULL,
  `col28` enum('failure','success','scheduled','died','canceled','killed') DEFAULT NULL,
  `col29` int unsigned DEFAULT '0',
  `col30` varchar(32) DEFAULT NULL,
  `col31` smallint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`col1`),
  KEY `col15` (`col15`),
<SNIP more btree indexes>
) ENGINE=InnoDB AUTO_INCREMENT=2514602429 DEFAULT CHARSET=latin1 |
```

**Backup log from another instance**:
```
2024-09-03 05:28:24 [INFO] - MyDumper backup version: 0.16.6-2
2024-09-03 05:28:24 [INFO] - Using 12 dumper threads
2024-09-03 05:28:24 [INFO] - Connection via default library settings using password:
        Socket: /path/to/socket
        User: root
2024-09-03 05:28:24 [INFO] - Connected to Percona 8.0.31
2024-09-03 05:28:25 [INFO] - Started dump at: 2024-09-03 05:28:25
2024-09-03 05:28:25 [INFO] - Stopping replica
2024-09-03 05:28:25 [INFO] - Written slave status
2024-09-03 05:28:25 [INFO] - Acquiring DDL lock
2024-09-03 05:28:25 [INFO] - LOCK INSTANCE FOR BACKUP: OK
2024-09-03 05:28:25 [INFO] - Acquiring Global lock
2024-09-03 05:28:25 [INFO] - FLUSH NO_WRITE_TO_BINLOG TABLES: OK
2024-09-03 05:28:25 [INFO] - FLUSH TABLES WITH READ LOCK: OK
2024-09-03 05:28:25 [INFO] - conf created
2024-09-03 05:28:25 [INFO] - End job creation
2024-09-03 05:28:25 [INFO] - Creating workers
2024-09-03 05:28:25 [INFO] - Starting Non-InnoDB tables
2024-09-03 05:28:25 [INFO] - Thread 1: connected using MySQL connection ID 385534
2024-09-03 05:28:25 [INFO] - Thread 2: connected using MySQL connection ID 385535
2024-09-03 05:28:25 [INFO] - Thread 3: connected using MySQL connection ID 385536
2024-09-03 05:28:25 [INFO] - Thread 4: connected using MySQL connection ID 385537
2024-09-03 05:28:25 [INFO] - Thread 5: connected using MySQL connection ID 385538
2024-09-03 05:28:25 [INFO] - Thread 6: connected using MySQL connection ID 385539
2024-09-03 05:28:25 [INFO] - Thread 7: connected using MySQL connection ID 385540
2024-09-03 05:28:25 [INFO] - Thread 8: connected using MySQL connection ID 385541
2024-09-03 05:28:25 [INFO] - Thread 9: connected using MySQL connection ID 385542
2024-09-03 05:28:25 [INFO] - Thread 10: connected using MySQL connection ID 385545
2024-09-03 05:28:25 [INFO] - Thread 11: connected using MySQL connection ID 385543
2024-09-03 05:28:25 [INFO] - Thread 12: connected using MySQL connection ID 385544
2024-09-03 05:28:25 [INFO] - Thread 10: Creating Jobs
2024-09-03 05:28:25 [INFO] - Thread 9: Creating Jobs
2024-09-03 05:28:25 [INFO] - Thread 1: Creating Jobs
2024-09-03 05:28:25 [INFO] - Thread 4: Creating Jobs
2024-09-03 05:28:25 [INFO] - Thread 2: Creating Jobs
2024-09-03 05:28:25 [INFO] - Thread 3: Creating Jobs
2024-09-03 05:28:25 [INFO] - Thread 6: Creating Jobs
2024-09-03 05:28:25 [INFO] - Thread 7: Creating Jobs
2024-09-03 05:28:25 [INFO] - Thread 5: Creating Jobs
2024-09-03 05:28:25 [INFO] - Thread 11: Creating Jobs
2024-09-03 05:28:25 [INFO] - Thread 8: Creating Jobs
2024-09-03 05:28:25 [INFO] - Thread 12: Creating Jobs
2024-09-03 05:28:25 [INFO] - Waiting database finish
2024-09-03 05:28:25 [INFO] - Written master status
<SNIP>
2024-09-03 05:30:03 [INFO] - Thread 11: `$db2`.`$table1` [ 91% ] | Tables: 10/12
2024-09-03 05:30:03 [ERROR] - Thread 11: Could not read data from $db2.$table1 to write on /path/to/backup/mydumper/$S2-mydumper-090324_052824/db2.table1.00000.00491.sql at byte 1280303: Lost connection to MySQL server during query
2024-09-03 05:30:44 [ERROR] - Thread 11: Error dumping table ($db2.$table2) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db2`.`$table2`  WHERE (525000000 <= `id` AND `id` <= 529999999)
2024-09-03 05:30:44 [ERROR] - Thread 11: Error dumping table ($db2.$table2) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db2`.`$table2`  WHERE (530000000 <= `id` AND `id` <= 534999999)
2024-09-03 05:30:44 [ERROR] - Thread 11: Error dumping table ($db2.$table2) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db2`.`$table2`  WHERE (535000000 <= `id` AND `id` <= 539999999)
2024-09-03 05:30:44 [ERROR] - Thread 11: Error dumping table ($db2.$table2) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db2`.`$table2`  WHERE (540000000 <= `id` AND `id` <= 544999999)
2024-09-03 05:30:44 [ERROR] - Thread 11: Error dumping table ($db2.$table2) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db2`.`$table2`  WHERE (545000000 <= `id` AND `id` <= 549999999)
2024-09-03 05:30:44 [ERROR] - Thread 11: Error dumping table ($db2.$table2) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db2`.`$table2`  WHERE (550000000 <= `id` AND `id` <= 554999999)
2024-09-03 05:30:44 [ERROR] - Thread 11: Error dumping table ($db2.$table2) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db2`.`$table2`  WHERE (555000000 <= `id` AND `id` <= 559999999)
2024-09-03 05:30:44 [ERROR] - Thread 11: Error dumping table ($db2.$table2) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db2`.`$table2`  WHERE (560000000 <= `id` AND `id` <= 564999999)
2024-09-03 05:30:44 [ERROR] - Thread 11: Error dumping table ($db2.$table2) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db2`.`$table2`  WHERE (565000000 <= `id` AND `id` <= 569999999)
2024-09-03 05:30:44 [ERROR] - Thread 11: Error dumping table ($db2.$table2) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db2`.`$table2`  WHERE (570000000 <= `id` AND `id` <= 574999999)
2024-09-03 05:30:44 [ERROR] - Thread 11: Error dumping table ($db2.$table2) data: Lost connection to MySQL server during query
Query: SELECT /*!40001 SQL_NO_CACHE */ * FROM `$db2`.`$table2`  WHERE (575000000 <= `id` AND `id` <= 578328910)
```

Table structure for this case is:
```
| table2 | CREATE TABLE `table2` (
  `col1` int NOT NULL AUTO_INCREMENT,
  `col2` int DEFAULT NULL,                                                                                                                                   
  `col3` varchar(32) DEFAULT NULL,
  `col4` varchar(255) DEFAULT NULL,
  `col5` varchar(64) DEFAULT NULL,
  `col6` datetime DEFAULT NULL,
  `col7` varchar(64) DEFAULT NULL,
  `col8` mediumtext,
  `col9` varchar(16) DEFAULT NULL,
  `col10` tinyint(1) NOT NULL DEFAULT '0',
  `col11` varchar(64) DEFAULT NULL,
  `col12` enum('no','yes') DEFAULT 'no',
  `col13` enum('no','yes') DEFAULT 'no',
  `col14` varchar(64) NOT NULL DEFAULT '',
  `col15` int unsigned DEFAULT NULL,
  `col16` varchar(40) DEFAULT NULL,
  `col17` int DEFAULT NULL,
  `col18` int DEFAULT NULL,
  `col19` int DEFAULT NULL,
  `col20` varchar(64) DEFAULT NULL,
  `col21` varchar(64) DEFAULT NULL,
  `col22` tinyint(1) DEFAULT NULL,
  `col23` tinyint(1) DEFAULT NULL,
  `col24` int DEFAULT NULL,
  `col25` varchar(5) DEFAULT NULL,
  `col26` varchar(512) DEFAULT NULL,
  `col27` varchar(64) DEFAULT NULL,
  `col28` varchar(64) DEFAULT NULL,
  `col29` varchar(64) DEFAULT NULL,
  `col30` varchar(64) DEFAULT NULL,
  `col31` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`col1`),
  KEY `col10` (`col10`),
<SNIP more btree indexes>
) ENGINE=InnoDB AUTO_INCREMENT=245692412 DEFAULT CHARSET=latin1 MAX_ROWS=8692396 AVG_ROW_LENGTH=1814 PACK_KEYS=1 |
``` 
If I can provide additional information to help troubleshoot, let me know. Thank you!

**Comment by davidducos** [comment]
Hi @dreamydb 
From the MySQL documentations:
```
Usually it indicates network connectivity trouble and you should check the condition of your network if this error occurs frequently. If the error message includes “during query,” this is probably the case you are experiencing.
```
I think that you have network issues. Another thing that call my attention is that every single time that failed, it was at a similar byte position, 1 MB. I would recommend you to check the mtu at network layer.

**Comment by dreamydb** [comment]
Mydumper versions `0.9.5-1.1` or `0.14.5-2` or `0.16.1-3` don't get these errors. Everything remains the same (db, script, backup location, network etc). If it were network other versions would fail too.

**Comment by davidducos** [comment]
Hi @dreamydb are you still having this issue?

**Comment by dreamydb** [comment]
Hi, we pinned mydumper version to `0.15.1-3` on all mysql machines and it works with no errors.  We have a machine upgraded to Ubuntu Noble with mydumper `0.17.1-1`.  Unfortunately, backups on some instances are taking way longer when compared to `0.15.1-3` with the same data, same mydumper options.  Also, a myloader restore of the `0.17.1-1` results in errors like this and causes replication to break after the restore on the replica.  I'll open a new ticket for all that since its not related to this one.

```
** (myloader:2258937): WARNING **: 11:44:44.778: Connection 55982: Warnings found during INSERT between lines: 8839848 and 8843699: (null)
** (myloader:2258937): WARNING **: 11:44:44.778: Connection 55979: Warnings found during INSERT between lines: 8843700 and 8847062: (null)
```

**Comment by davidducos** [comment]
Hi @dreamydb ,

Oh shit... I tried to reproduce this issue multiple times without luck. About v0.17.1-1 taking longer, you could try with the latest prerelease which might solve that issue, or you can wait until we release a new version which might be available this week.

**Comment by dreamydb** [comment]
Ah, that's good news!  I'll wait for the new version release.  Is there a bug report with similar issue of longer backup time reported you think is solved in the latest pre-release?

**Comment by davidducos** [comment]
Hi @dreamydb,
There might be one or two that might hit you if you are using large tables with integer primary key. Try to take backups avoiding `-r` if you can, as it is automatically set on the latest releases.

**Comment by davidducos** [comment]
Hi @dreamydb, 
can you test with the latest release, so we can close this issue?

**Comment by taeemo** [comment]
I'm getting the same issue with latest `v0.19.1-3` or `0.18.2-10`, but as mentioned above, with `0.15.1-3` it works fine. The restore process usually takes ~1-2 hours. But with the new versions it fails almost always around the same time (~26 in). This is all done against an AWS Serverless v2 (db config was not change in the last few months).

This is how we do the dump
`mydumper -h $host -u $username -p $password -B $schemaName --long-query-retries 1 -l 1800  --sync-thread-lock-mode=LOCK_ALL -o /tmp/dbdump -c -e -v 3`

And this is how we do the restore
`myloader -h 127.0.0.1 -u "$username" -p "$password" -B "$database" -d /tmp/dbdump -o -t 8 -q 10000 -C -v 3 --serialized-table-creation`

I attach the log & metadata, please let me know of any other info that I can provide to help with this issue.

[metadata.txt](https://github.com/user-attachments/files/19968945/metadata.txt)
[job-logs.txt](https://github.com/user-attachments/files/19968944/job-logs.txt)

**Comment by davidducos** [comment]
Hi @taeemo , can you take the backup compressing with zstd instead of the default gzip? you can do it with `-c ZSTD`

**Comment by davidducos** [comment]
Hi @taeemo ,
The log shows this at the end: 
```
[2025-04-29T21:17:40.000] [INFO] default -
** (myloader:2403): WARNING **: 21:17:39.999: Thread 12 using connection 1062591 - ERROR 2013: Lost connection to MySQL server during query

** (myloader:2403): CRITICAL **: 21:17:40.000: Error connection to database: Can't connect to MySQL server on '127.0.0.1:3306' (111)

[2025-04-29T21:17:41.326] [INFO] default - Trace/breakpoint trap (core dumped)
```
Which might be an indication that the server has crashed. BTW, how can this be a AWS Serverless v2 instance if you are connecting to 127.0.0.1 ? are you using a tunnel for the connection? Maybe the tunnel went down?

**Comment by davidducos** [comment]
Finally, you can use --show-warnings to see why you get so many of them unless you already now why you get them

**Comment by taeemo** [comment]
@davidducos with ZSTD it happens the same unfortunately :( - granted it happens after around 42 mins, but at roughly the same point/tables

`show global status like 'uptime';` returns 8907562, so ~100 days, so no, the server didn't die.

With the same backup, just switching between those versions, it breaks

**Comment by davidducos** [comment]
Hi @taeemo , can you share with me the ls of the backup dir? As the main difference between version is the implementation of pipes for compression. Maybe if you set -q to 10, it will go through.
Can you test without compression?

**Comment by davidducos** [comment]
Hi @taeemo, I have just realized that the error is not on a Data thread!! as all of them had finished:
```
➜  ~ grep "Data import ended" Downloads/job-logs.txt
[2025-04-29T21:07:38.991] [INFO] default - ** Message: 21:07:38.990: Thread 7: Data import ended
[2025-04-29T21:07:39.203] [INFO] default - ** Message: 21:07:39.203: Thread 6: Data import ended
[2025-04-29T21:07:39.415] [INFO] default - ** Message: 21:07:39.414: Thread 8: Data import ended
[2025-04-29T21:07:39.630] [INFO] default - ** Message: 21:07:39.629: Thread 5: Data import ended
[2025-04-29T21:07:39.699] [INFO] default - ** Message: 21:07:39.699: Thread 4: Data import ended
[2025-04-29T21:07:44.386] [INFO] default - ** Message: 21:07:44.385: Thread 3: Data import ended
** Message: 21:11:50.709: Thread 2: Data import ended
[2025-04-29T21:12:36.614] [INFO] default - ** Message: 21:12:36.613: Thread 1: Data import ended
```
The threads that is failing is Thread 12, which is a index restore thread. Do you see any entry in the MySQL error log?

**Comment by Blueblazer172** [comment]
I have the same (or maybe another?) problem with an import. Data import i assume works, but restoring the indexes failes always.

```
** Message: 08:18:58.889: Thread 80: restoring indexes dbname.tablename from index. Tables 350 of 377 completed
** Message: 08:18:58.890: Thread 84: restoring indexes dbname.tablename from index. Tables 350 of 377 completed
** Message: 08:18:58.890: Thread 87: restoring indexes dbname.tablename from index. Tables 350 of 377 completed
** Message: 08:18:58.890: Thread 82: restoring indexes dbname.tablename from index. Tables 350 of 377 completed
** Message: 08:18:58.890: Thread 86: restoring indexes dbname.tablename from index. Tables 350 of 377 completed
** Message: 08:18:58.890: Thread 89: restoring indexes dbname.tablename from index. Tables 350 of 377 completed
** Message: 08:18:58.890: Thread 91: restoring indexes dbname.tablename from index. Tables 350 of 377 completed

** (myloader:3316871): WARNING **: 08:20:52.499: Thread 73 using connection 172409 - ERROR 2013: Lost connection to MySQL server during query

** (myloader:3316871): WARNING **: 08:20:52.499: Thread 72 using connection 172393 - ERROR 2013: Lost connection to MySQL server during query

** (myloader:3316871): WARNING **: 08:20:52.499: Thread 67 using connection 172405 - ERROR 2013: Lost connection to MySQL server during query

** (myloader:3316871): WARNING **: 08:20:52.499: Thread 81 using connection 172414 - ERROR 2013: Lost connection to MySQL server during query

** (myloader:3316871): WARNING **: 08:20:52.499: Thread 89 using connection 172410 - ERROR 2013: Lost connection to MySQL server during query

** (myloader:3316871): WARNING **: 08:20:52.499: Thread 78 using connection 172407 - ERROR 2013: Lost connection to MySQL server during query
```
 The myloader command i use is the following:

```
myloader --host <ip> --user <user> -a --database <dbname> --directory /dir/ --verbose 3 -t 32 --overwrite-unsafe --queries-per-transaction 2000000000 --rows 0 --max-threads-for-index-creation 32 --optimize-keys AFTER_IMPORT_ALL_TABLES --max-threads-for-schema-creation 32
```
The Database I import is about 60GB in size.

```
myloader -V
myloader v0.19.1-3, built against MySQL 8.4.5 with SSL support
```

**Comment by davidducos** [comment]
Hi @Blueblazer172 , yes, it might be the same. Did you check the error log? do you see any entry there?

**Comment by dreamydb** [comment]
> Hi [@dreamydb](https://github.com/dreamydb), can you test with the latest release, so we can close this issue?

Sorry for the delay.  Tried the latest version `0.19.1-3` with a few changes.  Previously, used following options and it took over 4 hours.

```
mydumper --rows=5000000 --compress --build-empty-files --long-query-guard=1200 --verbose=3 --threads=12 --regex ^(?!(information_schema|mysql|sys)) --user=root --password=XXXXXXXX --socket=/path/to/socket --outputdir=/path/to/output --logfile /path/to/logfile
``` 

The table it takes the longest on is 53G with 5299343 rows.  Its table structure is:

```
 CREATE TABLE `A` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `TId` bigint NOT NULL,
  `P` bigint NOT NULL DEFAULT '0',
  `M` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `S` varchar(255) DEFAULT NULL,
  `Fi` varchar(255) DEFAULT NULL,
  `Co` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `Con` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `Cont` longblob,
  `H` longtext,
  `Cr` int NOT NULL DEFAULT '0',
  `Created` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `A2` (`TId`),
  KEY `A3` (`P`,`TId`),
  KEY `A1` (`Fi`)
) ENGINE=InnoDB AUTO_INCREMENT=5382498 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
``` 
mydumper output looks like a sea of:
```
2025-06-06 10:00:08 [INFO] - Thread 10: `db`.`A` [ 123% ] | Tables: 0/43
2025-06-06 10:00:13 [INFO] - Thread 10: `db`.`A` [ 123% ] | Tables: 0/43
2025-06-06 10:00:18 [INFO] - Thread 10: `db`.`A` [ 124% ] | Tables: 0/43
2025-06-06 10:00:25 [INFO] - Thread 10: `db`.`A` [ 124% ] | Tables: 0/43
2025-06-06 10:00:30 [INFO] - Thread 10: `db`.`A` [ 124% ] | Tables: 0/43
``` 

Good news!  With no `--rows` option and `--trx-tables` added, backup completes with no errors or lost connection messages in under 20mins!  
```
mydumper --compress --build-empty-files --triggers --events --routines --trx-tables --long-query-guard=1800 --verbose=3 --threads=12 --regex ^(?!(information_schema|mysql|sys)) --user=root --password=XXXXXXXX --socket=/path/to/socket --outputdir=/path/to/output --logfile /path/to/logfile
```

I'll be testing this version on other mysql instances also and report back if they hit the issues discussed in this ticket.  

Thank you for your support and time!

**Comment by dreamydb** [comment]
> Hi [@dreamydb](https://github.com/dreamydb), There might be one or two that might hit you if you are using large tables with integer primary key. Try to take backups avoiding `-r` if you can, as it is automatically set on the latest releases.

Sorry, this is a bit of a tangent from the actual issue in this bug.  After removing `--rows=5000000` and adding `--trx-tables` to the backup script, it works on most mysql instances with mydumper version at `0.18.1-1` or latest `0.19.1-3`.  Made the backup faster too.  Not on all mysql instances though.  On one instance, what used to take 15mins with --rows flag, took 1.5hours without and wrote an entire 29G logfile!!  That happens with both `0.18.1-1` or latest `0.19.1-3`. 

```
# Before script change, egrep 'version|Started|Finished' *.log
db1-mydumper-060725_063101.log:2025-06-07 06:31:01 [INFO] - MyDumper backup version: 0.18.1-1
db1-mydumper-060725_063101.log:2025-06-07 06:31:01 [INFO] - Started dump at: 2025-06-07 06:31:01
db1-mydumper-060725_063101.log:2025-06-07 06:43:53 [INFO] - Finished dump at: 2025-06-07 06:43:53
db1-mydumper-060825_063101.log:2025-06-08 06:31:01 [INFO] - MyDumper backup version: 0.18.1-1
db1-mydumper-060825_063101.log:2025-06-08 06:31:01 [INFO] - Started dump at: 2025-06-08 06:31:01
db1-mydumper-060825_063101.log:2025-06-08 06:43:39 [INFO] - Finished dump at: 2025-06-08 06:43:39
db1-mydumper-060925_063101.log:2025-06-09 06:31:01 [INFO] - MyDumper backup version: 0.18.1-1
db1-mydumper-060925_063101.log:2025-06-09 06:31:01 [INFO] - Started dump at: 2025-06-09 06:31:01
db1-mydumper-060925_063101.log:2025-06-09 06:45:32 [INFO] - Finished dump at: 2025-06-09 06:45:32

# Below result after the script change:
db1-mydumper-060925_084920.log:2025-06-09 08:49:20 [INFO] - MyDumper backup version: 0.18.1-1
db1-mydumper-060925_084920.log:2025-06-09 08:49:20 [INFO] - Started dump at: 2025-06-09 08:49:20
db1-mydumper-060925_084920.log:2025-06-09 10:20:39 [INFO] - Finished dump at: 2025-06-09 10:20:38

# Listing of backup and logfile sizes:
37G     db1-mydumper-060725_063101
882K    db1-mydumper-060725_063101.log
37G     db1-mydumper-060825_063101
882K    db1-mydumper-060825_063101.log
37G     db1-mydumper-060925_063101
882K    db1-mydumper-060925_063101.log
37G     db1-mydumper-060925_084920
29G     db1-mydumper-060925_084920.log
``` 
Looks like we can't ditch `--rows` from our script.  Any downsides to using it?  Other than this, the newest version `0.19.1-3` itself with --rows works fine, no errors so far.  I'll keep a close eye for a week and report if there are any issues.

**Comment by davidducos** [comment]
Hi @dreamydb ,
sorry to hear that newest version `v0.19.1-3` increases the backup timings. I think that you can try with `--use-single-column`, as you might have multi column primary key tables. On the other hand, it will be really useful for me if I can review a portion of the 29G log file to understand the issue, but before that, it might be possible that your bug has been already fixed on the prerelease [v0.19.2-4](https://github.com/mydumper/mydumper/releases/tag/v0.19.2-4). Please, let me know if you can test with v0.19.2-4 or if you need a release, as I will be releasing v0.19.3-1 soon.

**Comment by dreamydb** [comment]
Hi @davidducos,

From the logfile, it does look like mydumper is taking most time on tables with multi column primary keys.   One such table is 9G in size with 75298644 rows and following structure.  mydumper log shows it spent ~30mins on that one table.
```
CREATE TABLE usp (
  `us_id` bigint NOT NULL DEFAULT '0',
  `p` varchar(32) NOT NULL DEFAULT '',
  `v` varchar(128) NOT NULL DEFAULT '',
  `t` text,
  PRIMARY KEY (`us_id`,`p`,`v`),
  KEY `p_v` (`p`,`v`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 
``` 

Just tried your suggestion to use `--use-single-column`, it was still much slower than the 0.18 version.  In summary:

- With `--rows=5000000` and `v0.18.1-1` backup completes in 15mins.
 
All of the below combinations take much longer. 
- With `--rows=5000000` and `v0.19.1-3`
- No `--rows`, both versions `v0.18.1-1` and `v0.19.1-3`.
- With `--rows=5000000` and `--use-single-column`, `v0.19.1-3` still takes long. (option not present in `0.18.1-1`)

Is there open reports for something similar that will get fixed with next release?  Thank you.

**Comment by davidducos** [comment]
Hi @dreamydb , yes, next release will include https://github.com/mydumper/mydumper/pull/1882 which fixes your issue or you can use https://github.com/mydumper/mydumper/releases/tag/v0.19.2-4 to confirm that new release will work. 
I will try to release the new version this week.

**Comment by lkraav** [comment]
0.19.3-1: `--use-single-column` has also allowed mydumper to complete backup here that would otherwise hang for no clear reason. Compound / Multi-column primary keys are in play here.

But based on the above, I would've expected something related fixed in 0.19.2-4, but AFAICT 0.19.3-1 still fails?

**Comment by davidducos** [comment]
Hi @lkraav , 
can you share a reproducible test case for the issue? so I can understand where the issue might be?

**Comment by davidducos** [comment]
Closing til we get a reproducible test case
